"""empty message

Revision ID: 14e8123683ae
Revises: 6c597670622b
Create Date: 2020-05-12 15:58:39.699830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e8123683ae'
down_revision = '6c597670622b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'test')
    # ### end Alembic commands ###
